### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MuzsaiLajos** [MuzsaiLajos/UnifiedLog#1]
Még kell

- [ ] Model pipeline new figure
- [ ] Dropout
- [ ] Leave 1 on one
- [ ] Leave 1 on all
- [ ] Leave 5
- [ ] Embed dim
- [ ] Number of heads
